openshift/ironic-agent-image

Dockerfile

Copying an object in the container preserves its name.

[trivial] use same name for hardware_manager

---

Dockerfile.ocp

The AS in the FROM instruction generates a multi layered image that is
not reused anywhere in the Dockerfile, it's not needed and it prevents
the correct build of the final container image.
Also copying hardware_manager doesn't require filename destination.

Correct FROM entry in Dockerfile.ocp

---

Dockerfile
Dockerfile.ocp

Image building fails after it with:
pip.exceptions.InstallationError: Invalid requirement: '/tmp/hardware_manager'
It looks like a path. Does it exist ?

Revert the COPY hardware_manager change

---

README.md
hardware_manager/ironic_coreos_install.py

Changes for https://github.com/metal3-io/metal3-docs/pull/180:
* Pass parameters through configdrive and standard instance_info
* Add error handling

Rework the install_coreos deploy step per approved design

---

hardware_manager/ironic_coreos_install.py

Get rid of the default config generated by NetworkManager during the IPA boot, since it currently limits us to DHCP on only one interface (the wrong one). This is a workaround for https://bugzilla.redhat.com/show_bug.cgi?id=2032717
Since the default config will not be persisted, we need to copy and `ip=dhcp`/`ip=dhcp6` kernel options passed to the IPA boot to the installed OS.

Fix the default network config for the installed OS

---

hardware_manager/ironic_coreos_install.py

The correct IP options (ip=dhcp vs. ip=dhcp6) may be different for the
IPA phase vs. the actual installed system, since the network used to
communicate back to ironic and the network used to fetch the Ignition on
boot of the installed image may be different.
Allow the environment variable IPA_COREOS_IP_OPTIONS to specify a kernel
arg to append in the installed system.

Bug 2034527: Allow setting IP options kernel args on install 

---

hardware_manager/ironic_coreos_install.py

If the user does not provide any network config, then a `default_connection.nmconnection` file created by network manager during early boot gets copied out of dracut. On PXE boots this file [limits us to using only the PXE interface](https://bugzilla.redhat.com/show_bug.cgi?id=2032717), which is something we don't want to do after installation.
To work around this, in #27 we started deleting the default connection before installing. However, this means that the user cannot supply a default connection either.
Instead, leave the default_connection file alone and only pass --copy-network if the user has provided a network config.

Bug 2038303: Allow customisation of default_connection file

---

hardware_manager/ironic_coreos_install.py
packages-list.ocp
packages-list.okd

This step starts the assisted agent unit so that the rest of the install
process can be managed by AIA.
Signed-off-by: Flavio Percoco <flavio@redhat.com>

Add an start_assisted_install step

---

hardware_manager/ironic_coreos_install.py

Testing proved to need more retries on the HW where we could
reproduce this problem

Bug 2086759: Bump retries for UEFI boot configuration

---

hardware_manager/ironic_coreos_install.py

This wasn't part of a recent cherry-pick as time
was already imported in origin/main but hadn't
been in release-4.10
We need to import it here

Bug 2053752: import time

---

packages-list.ocp

Ironic inspector image fails to clean disks that are
part of a multipath setup if they are passive paths

Bug 2089309: multipath fix for passive paths

---

packages-list.ocp

The latest ipa package includes the change
https://review.opendev.org/c/openstack/ironic-python-agent/+/847155
that should be included in OCP 4.11

Bug 2098392: Include Fix discovering WWN/serial for devicemapper devices

---

packages-list.ocp
packages-list.okd

Multipath modules are missing therefore multipath configuration can't be
correctly activated.

Bug 2100749: Add missing multipath modules

---

packages-list.ocp
packages-list.okd

Multipath modules are missing therefore multipath configuration can't be
correctly activated.

Bug 2100836: Add missing multipath modules

---

packages-list.ocp

The latest ipa package includes the change
https://review.opendev.org/c/openstack/ironic-python-agent/+/847552
that should be included in OCP 4.10

Bug 2100775: Include Fix discovering WWN/serial for devicemapper devices

---

packages-list.ocp
packages-list.okd

It's not installed by default in rhel9

Install iproute explicitely

---

packages-list.ocp

Upgrade to a IPA package that includes the change
https://review.opendev.org/c/openstack/ironic-python-agent/+/848867

[release-4.10] OCPBUGS-1232: Include Fix for discovering bond interfaces

---

hardware_manager/ironic_coreos_install.py

Currently it goes to stdout, which is handy for observing it in real
time, but leaves no traces in the logs. Read from stdout/stderr and
direct messages to the logs as they arrive. Also use the last line
as an error message.

OCPBUGS-4899: make coreos-installer output available in the logs

---

packages-list.ocp

The dnf command should be able to figure out the correct package needed for the udevadm command to be present.

"Bug OCPBUGS-15447: Switch to udevadm command install instead of package"

---

hardware_manager/ironic_coreos_install.py

The old versions of hostnamectl don't have the "hostname" command,
parse the output of "status" instead.

OCPBUGS-19008: better compatibility with old hostnamectl

---

hardware_manager/ironic_coreos_install.py

Regardless of how IPA got to the point of finding a hostname we need it to match the hostname after its provisioned.

OCPBUGS-19008: Always add ignition to set hostname on /etc/hostname

---

ironic-python-agent.conf
packages-list.ocp
packages-list.okd

Not used in BMO since https://github.com/metal3-io/baremetal-operator/pull/1297.

METAL-913: drop dependency on python-hardware

---

requirements.cachito

bring in fix for 4096 bytes sector disks

OCPBUGS-33133: update ironic-lib with latest fixes

---

requirements.cachito

bring in fix for 4096 bytes sector disks

OCPBUGS-33452: update ironic-lib with latest fixes

---

prepare-image.sh

Installing compiled python files through pip can cause issues in FIPS-enabled environments. This change disables installing those files through pip and compiles them locally instead.

OCPBUGS-35968: Disable installation of .pyc files through pip

---

prepare-image.sh
requirements.cachito

Since in CI we use the --no-index option to emulate a pip disconnected environment to try and reproduce the downstream build conditions, it's not possible to test normal dependencies from source as pip won't be able to retrieve them from any remote source.
To work around that we download all the packages first removing the --no-index option but using the --no-deps option, preventing downloading dependencies.
This forces to download only the packages specified in the requirements file, ensuring total control on main libraries and dependencies and allowing us to be as granular as needed, easily switching between RPMs and source packages for testing or even for downstream builds.
When we install them afterwards if any dependency is missing the installation process will fail in CI, allowing …

METAL-1049: Download and install sources from local dir

---

.ci-operator.yaml

Most recent available is still from 4.17 but we should update it to avoid errors in the pipeline as the current one is too old.

OCPBUGS-38406: Update root image

---

.ci-operator.yaml

we should update it to avoid errors in the pipeline as the current one is too old.

OCPBUGS-38481: Update root image

---

packages-list.ocp

OCPBUGS-38521: set webob and bump werkzeug

---

packages-list.ocp

[4.16] OCPBUGS-38510: set webob and bump werkzeug

---

packages-list.ocp

[4.15] OCPBUGS-38512: set webob and bump werkzeug

---

packages-list.ocp

[4.14] OCPBUGS-33375: set webob and bump werkzeug

---

packages-list.ocp

[4.13] OCPBUGS-38509: set webob and bump werkzeug

---

packages-list.ocp

[4.12] OCPBUGS-38513: set webob and bump werkzeug

---

hardware_manager/ironic_coreos_install.py
packages-list.ocp
prepare-image.sh
requirements.cachito

Latest IPA removes the netifaces dependency
Import disk_utils from IPA as it was moved a while ago
from ironic-lib

METAL-1155: Update to latest ironic projects hash for OCP 4.18

---

prepare-image.sh

Get system installed build dependencies also during pip download to avoid installing them from source.

METAL-1164: Add pip no-build-isolation to download command

---

hardware_manager/ironic_coreos_install.py

When no other ignition exists we need to create it from scratch with a version number.

OCPBUGS-43546: Add ignition version number

---

Dockerfile.ocp

They conflict with our owns and we don't use them in production so the builds are completely different between CI and production actually making the tests completely unreliable.

METAL-1299: Do not use openstack packages

---

Dockerfile.ocp

They conflict with our owns and we don't use them in production so the builds are completely different between CI and production actually making the tests completely unreliable.
(cherry picked from commit 5ca78f787310edac32746b8358e45b1028d81660)

METAL-1305: Do not use openstack packages

---

Dockerfile.ocp

They conflict with our owns and we don't use them in production so the builds are completely different between CI and production actually making the tests completely unreliable.
(cherry picked from commit 5ca78f787310edac32746b8358e45b1028d81660)

METAL-1306: Do not use openstack packages

---

hardware_manager/ironic_coreos_install.py

Currently, we evaluate the hostname when initializing the agent.
Apparently, it's possible for the real hostname to be determined later,
which causes a discrepancy between the hostname that is reported in
inspection (and set on Machine) and the hostname sent to the instance
via Ignition (and thus appearing on Node).
This change leaves the early hostname fix where it is but generates
hostname for Ignition where it is used.

OCPBUGS-55315: Delay determining the hostname to put into ignition

---

packages-list.ocp

This is to explicitely align with ironic-image dependencies

METAL-1574: Update deps pkgs versions
