openshift/ironic-agent-image

hardware_manager/ironic_coreos_install.py, prepare-image.sh, runironicagent
Leaving the following files intact:
- Dockerfile.ocp
- Dockerfile.okd
- OWNERS
- README.md
Commits included:
- OWNERS: add Iury, remove Julia
- Switch to CentOS Stream and fix the build
- Remove downstream Dockerfile
- Remove bz reference from OWNERS
- Update quay org to metal3-io
- Default to using --copy-network
- Run efibootmgr if boot mode is UEFI
- Apply local patches before removing git
- Fix the log_file option name
- Remove redundancy in OWNERS
=> Merge from metal3-io

Dockerfile.ocp, Dockerfile.okd, packages-list.ocp, packages-list.ocp-x86_64, packages-list.okd, packages-list.okd-x86_64, prepare-image.sh
This creates arch-specific package lists to handle those packages which are not available on all architectures.
/cc @elfosardo
=> Fix build on other architectures

packages-list.ocp
Include latest software and RPM spec changes.
=> Update ipa version

hardware_manager/ironic_coreos_install.py
This consistently fails on some HW, retry until we
find a proper solution.
=> Retry UEFI boot Configuration

hardware_manager/ironic_coreos_install.py
And a short sleep and an extra retry for some
extra reliability.
=> Update the retry to Configuring UEFI

hardware_manager/ironic_coreos_install.py
backport of 2 patches from master to deal with retries for UEFI boot configuration
=> Bug 2053752: Bump retries for UEFI boot configuration

packages-list.ocp
=> Bug 2089312: multipath fix for passive paths

packages-list.okd
Apply commit 68ea744 to OKD, too.
=> [main] Switch to udevadm command install instead of package [OKD]

packages-list.okd
Apply commit 68ea744 to OKD, too.
=> [release-4.13] Switch to udevadm command install instead of package [OKD]

hardware_manager/ironic_coreos_install.py
Revival of https://github.com/openshift/ironic-agent-image/pull/39 with some clean-up.
=> OCPBUGS-9072: Pass hostname within the ignition to coreos-installer

hardware_manager/ironic_coreos_install.py
1) Do not ignore UnitNotFound, it's not a normal state of things.
2) Handle and report the "failed" unit state.
3) Do not initialize DBus on each iteration.
=> OCPBUGS-14585: rework detection of the assisted agent

hardware_manager/ironic_coreos_install.py
- OCPBUGS-9072: Pass hostname within the ignition to coreos-installer
- OCPBUGS-17372: fallback to /etc/hostname if hostnamectl fails
Depends on:
- https://github.com/openshift/image-customization-controller/pull/98
=> OCPBUGS-19006: backport hostname fixes

packages-list.ocp
Bumping packages quickly to jump to very latest versions
=> OCPBUGS-23553: Update packages with latest fixes

packages-list.ocp
This commit contains the package with the workaround for the problem
=> OCPBUGS-16607: 502 Proxy Error

packages-list.ocp
The package tagged contains the workaround for this bug
=> OCPBUGS-25351: 502 proxy error

hardware_manager/ironic_coreos_install.py
Regardless of how IPA got to the point of finding a hostname we need it to match the hostname after its provisioned.
=> OCPBUGS-29725: Always add ignition to set hostname on /etc/hostname

packages-list.ocp
Update the version of openstack-ironic-python-agent
=> NO-ISSUE: Update openstack-ironic-python-agent version

Dockerfile.ocp, packages-list.ocp, prepare-image.sh, requirements.cachito, tools/check-requirements.sh
Also adds script to check requirement release match
=> METAL-925: Install ironic-python-agent from source

Dockerfile.ocp, Makefile, packages-list.ocp, prepare-image.sh, requirements.cachito, tools/check-requirements.sh
Plus add check-requirements and Makefile
=> OCPBUGS-32170: [4.14] Add hybrid configuration for cachito

README.md
Nobody really needs the old installation instructions, let's better talk
about the actual workflow. Also document the asssisted converged flow.
=> NO-ISSUE: Replace README with an explanation how this agent works

requirements.cachito, tools/check-requirements.sh
- Remove dependency from ironic-lib
- Silence errors from modprobe of various IPMI modules
=> OCPBUGS-45259: METAL-1251: Update commit hash of ironic-python-agent

hardware_manager/ironic_coreos_install.py
Currently, we evaluate the hostname when initializing the agent. Apparently, it's possible for the real hostname to be determined later, which causes a discrepancy between the hostname that is reported in inspection (and set on Machine) and the hostname sent to the instance via Ignition (and thus appearing on Node).
This change leaves the early hostname fix where it is but generates hostname for Ignition where it is used.
=> [4.17] OCPBUGS-55680: Delay determining the hostname to put into ignition

hardware_manager/ironic_coreos_install.py
IPA itself is only capable of collecting dmesg, which is not enough.
=> OCPBUGS-55350: collect the entire journal from the host
